### ISSUE TITLE
Any plans to support listing secrets?

### ISSUE THREAD

**Issue by zeljko-mirovic** [BetterCloud/vault-java-driver#12]
Do you have plans to support listing all secrets for URL? I will be willing to help.

**Comment by adkhare** [comment]
@zeljko-mirovic pls submit a pull request and we will be happy to get it reviewed and merged

**Comment by steve-perkins** [comment]
This is code-complete in `master`, and will go out with the 1.1.0 release.  However, the PKI-related functionality in 1.1.0 is very important to some other work we have going on internally... so it will be heavily tested for awhile, and probably won't be released to Maven Central in binary form until that other work is solid and verified.

**Comment by steve-perkins** [comment]
Version 1.1.0 is now up on Maven Central!  Support for listing secrets has been added to the `Logical` API class.
