### ISSUE TITLE
Tagging releases in git

### ISSUE THREAD

**Issue by jjlauer** [BetterCloud/vault-java-driver#13]
Just curious about releasing this to maven central w/o a corresponding tag in git?  We are looking to use your lib in production and we like to review version deltas.  W/o tags in git it makes a bit more difficult to confirm what's actually on maven central.

**Comment by steve-perkins** [comment]
The "0.3.0" branch represents the source state for the 0.3.0 release, and likewise the "0.5.0" branch for 0.5.0.  Had we issued any minor bugfix releases for either version (e.g. "0.5.1"?), we probably would have created tags within the particular branch.  However, so far we've been jumping straight to the next odd-numbered release version (the next will be 0.7.0).

**Comment by jjlauer** [comment]
So, it looks like you do development on master, then when you do a release, you branch it?  Why not just tag it from master at the same time?  You'd have clean v0.3.0, v0.5.0 tags then. If you do a release from a branch, tag that as well.  Consumers of the lib would nicely see a v0.5.1 tag even if that happened to be on a branch. To plan on only doing tags on hotfixes seems a bit unusual.

Again, I appreciate your work, just trying to get a grasp on the strategy here.

**Comment by jjlauer** [comment]
BTW, if you tag from master, you can always do a branch later directly from a tag.

`git branch new_branch tag_name`

So, really you could simplify everything by doing it master, tagging it on releases, and if you do need to do a hotfix, simply branch the tag, fix it, then eventually tag something in that branch or when you merge it back to master.

**Comment by steve-perkins** [comment]
We were just mirroring the branching practice that we use for non-open, internal repos.  I'm happy to start adding tags for releases.  Looking at some docs, would "annotated" tags be preferable, or "lightweight"?

https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by jjlauer** [comment]
Yeah, that's exactly what would be great.  You don't even need to annotate
the tag unless you wanted to supply more info.

-Joe

**Comment by steve-perkins** [comment]
Tags now created for the 0.3.0 and 0.5.0 releases.  

The next release, hopefully going out today, will be 1.0.0.  It was initially going to be 0.7.0, but there are some minor breaking changes... so we're incrementing the major version number accordingly.  I'll tag that commit when it goes out.

Let me know if there's anything else needed on this, and if not then I'll come along and close the issue later (or feel free to close it yourself).  Thanks!
