### ISSUE TITLE
JDK11 support?

### ISSUE THREAD

**Issue by MansurAshraf** [BetterCloud/vault-java-driver#145]
Hello,

Are there plans to upgrade vault driver to JDK11?

**Comment by steve-perkins** [comment]
There are no current plans to drop Java 8 compatibility.  However, PR #165 was just merged yesterday, which should hopefully address Java 11 support as well.  That binary artifact should go up to Maven Central tomorrow.  If there are any issues, ping me and I can reopen this issue.
