### ISSUE TITLE
Tag 4.0.0 :)

### ISSUE THREAD

**Issue by casz** [BetterCloud/vault-java-driver#154]
No tag for 4.0.0

**Comment by jhoblitt** [comment]
This caused me some serious head scratching...

**Comment by steve-perkins** [comment]
Thanks, done!

Although curiously enough, the "Releases" tag still designates v3.1.0 as being "Latest Release".  I don't see any way to change this, and a bit of web searching suggests that you *can't*.  That GitHub determines this automatically based on the timestamp of the tagged commit.  Which is still mysterious, as v3.1.0 was committed and tagged in 2018, and the v4.0.0 commit and tag are from 2019.

At any rate, there should be a v4.1.0 going up tomorrow, so hopefully the "Latest Release" designation will self-correct accordingly for that release.

**Comment by casz** [comment]
@steve-perkins you have to create a "new release" and select the tag v4.0.0
This explains how: https://help.github.com/en/articles/creating-releases

**Comment by steve-perkins** [comment]
Clunky.  The mere act of adding a tag causes GitHub to create a release (this is how I've generated all of the previous ones).  This "Latest Release" designation seems to be something fairly recent.  To move that, you apparently have to manually generate a release with the same name, to clobber the release that was just auto-created.
