### ISSUE TITLE
Any plan to support delete?

### ISSUE THREAD

**Issue by arnabguptadev** [BetterCloud/vault-java-driver#16]
Nice, simple API. Thanks! Any plan to support delete?

**Comment by steve-perkins** [comment]
Are you talking about down in the REST layer in general (definitely yes!)... or are you talking about a specific operation up in the Vault layer?

**Comment by steve-perkins** [comment]
If this is talking about DELETE operations in the REST layer, or deleting secrets in the Logical API wrapper... both are code-complete in master, and will go out with the 1.1.0 release. 

However, the PKI-related functionality in 1.1.0 is very important to some other work we have going on internally... so it will be heavily tested for awhile, and probably won't be released to Maven Central in binary form until that other work is solid and verified.

**Comment by josegom** [comment]
Hello, 

I am very interested to know if you have any release date for this functioanlity or if you have any plan to release a Snapshot or something like it soon.

Thanks.

**Comment by ZeeShen** [comment]
Waiting for new release, too.

**Comment by tiagojco** [comment]
+1 waiting for the new release
Good job btw

**Comment by steve-perkins** [comment]
Version 1.1.0 is now up on Maven Central!  Support for deleting secrets has been added to the `Logical` API class.

**Comment by evenh** [comment]
Awesome! Do you mind creating a tag as well?

**Comment by arnabguptadev** [comment]
Thanks a lot!
