### ISSUE TITLE
Logging is done through System.out.println

### ISSUE THREAD

**Issue by arngrimur-seal** [BetterCloud/vault-java-driver#177]
Logging using System.out.println is bad. It is not possible to filter and spams the test and production logs. Use java.util.logging (or better slf4j) instead of println for logging. This enables configurable logging and will still keep the project dependency free.

**Comment by steve-perkins** [comment]
Agreed.  The associated PR has been merged, and I've updated the README to reflects its inclusion in the (still pending) 4.2.0 release.
