### ISSUE TITLE
Clarification on prefixPath

### ISSUE THREAD

**Issue by jbcraig** [BetterCloud/vault-java-driver#223]
The term prefixPath is a bit confusing for me.  Am I correct that this value should be set to the KV2 secret engine path value (previously referred to as mount-point) and only comes into play with KV2 secrets?  

Thanks, your efforts and accomplishments are appreciated.

**Comment by rtib** [comment]
It's the length, i.e. the number of slashed, of the mount point name where the KV2 engine is mounted on. The vault CLI client is acquiring this by requesting `/sys/mounts` for every request.
