### ISSUE TITLE
Add support for /auth/token/create/[role_name] in Auth

### ISSUE THREAD

**Issue by alexku-o** [BetterCloud/vault-java-driver#27]
Hi there,

Vault introduced the concept of [roles in 0.6.0](https://www.hashicorp.com/blog/vault-0.6.html#token-auth-roles), with a new auth API endpoint in `/auth/token/create/[role_name]`. It'll be good if the Auth class would support a method that hits that endpoint directly.

I am internally writing something to provide this, and I'll look to submit a PR at a later date if others haven't gotten to it yet later.

Thanks,
Alex

**Comment by alexku-o** [comment]
Hi @steve-perkins-bc,

Sorry to trouble you - is there an ETA for the `1.2.0` release?

Reason I ask is that I'm trying to see if it makes sense for me to push a PR through in the next couple days for this issue, to enable token creation for roles (as opposed to punting on that and keeping the code internally). That's largely depend on all of the following conditions being true:

1. if we may, commit some kind attention from BC's end for a PR on this issue (that I can submit) over the next day or two,
2. 1.2.0 is about to be released, and 
3. the fix for this issue can be made into the 1.2.0 release

I'll appreciate your comments on this greatly.

Thanks,
Alex

**Comment by steve-perkins** [comment]
I was planning to get 1.2.0 out later this week.  If you can get a PR in by Thursday, then maybe it can get out with that release.  

Either way, version 2.0 will follow shortly thereafter.  A lot of stuff is getting marked as deprecated in version 1.2.0, and so there needs to be a breaking-change major release to actually remove all that deprecated stuff.  If you can't make 1.2.0 then you can certainly make 2.0.

**Comment by alexku-o** [comment]
Thanks @steve-perkins. I'll doubly confirm with the team on our schedule and report back asap. Updates to follow. Thanks again!

**Comment by steve-perkins** [comment]
Just going through and cleaning up open issues.  If this still something that you'd like to submit some code for, then I'll be happy to review the pull request when it comes in.  Closing this ticket for now.  Thanks!

**Comment by steve-perkins** [comment]
Oh, I'm not sure if this is the same organization, or some other party with the same need, but it looks like pull request #41 involves the functionality discussed here.

That PR currently has a merge conflict.  However, I've already reviewed it, and expect to merge it once the conflict is resolved.
