### ISSUE TITLE
Add support for AppRole authentication backend

### ISSUE THREAD

**Issue by jchambers** [BetterCloud/vault-java-driver#34]
I know it's [already a TODO](https://github.com/BetterCloud/vault-java-driver/blob/master/src/main/java/com/bettercloud/vault/api/Auth.java#L151-L152), but it'd be great to add support for the [AppRole authentication backend](https://www.vaultproject.io/docs/auth/approle.html). I'm selfishly opening this ticket to track progress on the implementation ;)

**Comment by MyRealityCoding** [comment]
If nobody else is working on this I would like to open a PR to add support for it! :octocat:

**Comment by steve-perkins** [comment]
NOTE:  There's already a PR open for this (https://github.com/BetterCloud/vault-java-driver/pull/35).  

It will probably be a week or two before this gets reviewed and merged and a 2.0 release cut.  Most of the next release will consist of refactoring and removing deprecated stuff.

**Comment by steve-perkins** [comment]
Apologies for the lengthy delay on getting this PR reviewed and merged.  It's in `master` now, and I hope to release the next version of the library to Maven Central next week.
