### ISSUE TITLE
Add support for token renewal (sys/renew)

### ISSUE THREAD

**Issue by ckymdev9000** [BetterCloud/vault-java-driver#38]
It seems that /sys/renew functionality was left out from the Leases class. Was there a particular reason or just an oversight?

**Comment by steve-perkins** [comment]
It was a community-submitted pull request, and they only implemented the endpoints that they themselves needed.  I'm happy to circle back around and implement `/renew` myself, but it will probably be a few weeks before I get to it.

**Comment by ckymdev9000** [comment]
After further poking around, I see renewSelf() and renewSelf(long) in the Auth class, which is essentially what I was looking for.
The /sys endpoints operate on lease IDs. And the the /auth/token endpoints operate on tokens.
