### ISSUE TITLE
arbitrary object value serialization for write()

### ISSUE THREAD

**Issue by holmari** [BetterCloud/vault-java-driver#42]
Currently, logical().write() supports writing only string/string key-value pairs. However, Vault's API supports writing arbitrary JSON or YAML records into the database. In particular, this is important for arrays.

This API should reflect that, by changing the API as `write(String path, Map<String, Object> keyValuePairs)`. This would be a source compatible change, and the objects could be internally converted to JSON.

**Comment by steve-perkins** [comment]
This is now supported in `master`, and will go up to Maven Central in the `3.0.0` release (which is pending review and merge of a couple other pull requests).

**Comment by steve-perkins** [comment]
Version 3.0.0 has been pushed to Maven Central, with this functionality.  It should be indexed in Maven Central within the next few hours.
