### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by jcustenborder** [BetterCloud/vault-java-driver#45]
Hello there! Thanks for building this! Would it be possible to clarify the license? Maybe by adding a LICENSE file to the root of the repository?

**Comment by steve-perkins** [comment]
This library is under the MIT license.  There's a licensing stanza at the the bottom of the README.

**Comment by jcustenborder** [comment]
Thanks man! I totally missed that.

**Comment by steve-perkins** [comment]
No worries!
