### ISSUE TITLE
Add support for ldap login 

### ISSUE THREAD

**Issue by issacg** [BetterCloud/vault-java-driver#61]
It would be nice to have the ability to login to ldap

**Comment by issacg** [comment]
Fixed in #69

**Comment by issacg** [comment]
Seeing as #69 just missed a release, wondering if there's any estimated release date for an upstream version with this in place?

**Comment by laeubi** [comment]
If I understand it right from the code you should be able to use "Auth#loginByUserPass(String, String, 'ldap')"
