### ISSUE TITLE
[Documentation] Constructor of VaultConfig no longer accepts parameters

### ISSUE THREAD

**Issue by Naktibalda** [BetterCloud/vault-java-driver#66]
In v3.0.0 constructor of VaultConfig no longer accepts parameters.

> Result: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: com.bettercloud.vault.VaultConfig(java.lang.String, java.lang.String)

However the first 2 examples in documentation still use constructor parameters
https://github.com/BetterCloud/vault-java-driver/blob/v3.0.0/README.md#initializing-a-driver-instance

```java
final VaultConfig config = new VaultConfig("http://127.0.0.1:8200", "3c9fd6be-7bc2-9d1f-6fb3-cd746c0fc4e8");

// You may choose not to provide a root token initially, if you plan to use
// the Vault driver to retrieve one programmatically from an auth backend.
final VaultConfig config = new VaultConfig("http://127.0.0.1:8200");
```

**Comment by steve-perkins** [comment]
Thanks!  An update has been merged into `master`.  Since this is just a `README` change, this issue is effectively resolved since it's visible on the GitHub repo page right now.
