### ISSUE TITLE
Support for App-ID

### ISSUE THREAD

**Issue by shin-nien** [BetterCloud/vault-java-driver#7]
I took a quick look around the code and it looks like it's focussed around using tokens as the only auth method. I was wondering if there was any plan to support app-id?

We're running on Docker where passing the token via ENV doesn't seem to be the best of ideas. App-id seems like a reasonable compromise sitting in between cubbyhole and tokens.

**Comment by kunickiaj** [comment]
Version 0.5.0 does support app-id login.

Docs seem thin, but this is how I was able to get it to work:

```java
Vault vault = new Vault(config.build());
AuthResponse authResponse = vault.auth().loginByAppID(AUTH_PATH, APP_ID, USER_ID);
vault = new Vault(config.token(authResponse.getAuthClientToken()).build());
```

**Comment by shin-nien** [comment]
oh yeah...right there in the javadoc too. Thanks.
