### ISSUE TITLE
createToken missing explicit_max_ttl and renewable options

### ISSUE THREAD

**Issue by msbit01** [BetterCloud/vault-java-driver#75]
https://www.vaultproject.io/docs/auth/token.html#post includes options for an explicit_max_ttl and whether or not the token should be renewable. v3.0.0 of the vault-java-driver does not support these options. It would be great if these could be added.

Acceptance Criteria:
java-vault-driver should support all options for createToken

Suggested Tech Steps:
Update Auth.TokenRequest (https://github.com/BetterCloud/vault-java-driver/blob/2e00c2f9fc60ac342c57817cf92c640cdcb092f4/src/main/java/com/bettercloud/vault/api/Auth.java#L38) to take these parameters.

**Comment by bmudda** [comment]
+1

**Comment by bambambam** [comment]
+1
There is one more essential option "entity-alias" is also missing. I would make a PR to implement those. Please let me know if there are any concerns.

Thanks,
Spencer

**Comment by steve-perkins** [comment]
Addressed with pull request #199
