### ISSUE TITLE
Support Response Wrapping

### ISSUE THREAD

**Issue by VladRassokhin** [BetterCloud/vault-java-driver#78]
There's great feature introduced recently named '[Resource Wrapping](https://www.vaultproject.io/docs/concepts/response-wrapping.html)'.
It would be useful to support in in Java client library.

Use case: 
1. Service A authenticates with `/auth/approle/login` endpoint providing App Role role_id, secret_id and ` X-Vault-Wrap-TTL` header.
2. Response contains AccessorID and WrappedTokenID, first one left on Service A, second passed to Service B.
3. Service B connects to Vault server and performs GET on `/sys/wrapping/unwrap?token=${WrappedTokenId}` and receives proper token, then reconfigures itself and proceeds with operations.

Example was shown during [Securing Applications Using Nomad
](https://youtu.be/4gAYyAA6h9E?t=31m58s) presentation.

**Comment by dubreuia** [comment]
Bump. Will that be implemented at some point? Thanks.

**Comment by nano4711** [comment]
+1 for this request!

**Comment by dubreuia** [comment]
WIP PR implemented. I'm only supporting unwraping auth token for now.

**Comment by dubreuia** [comment]
More I think about it, more I think it should be a root operation like `Vault#unwrap(String)` instead of `Auth#unwrap(String)` like I implemented it. Who's the maintainer? @steve-perkins?

**Comment by nano4711** [comment]
Wow, that was fast. PR looks great. Hope it will be accepted soon!

**Comment by dubreuia** [comment]
I added `Auth#unwrap()` to unwrap a login token without logging in. Also more documentation and unit tests.

**Comment by dubreuia** [comment]
I added `Auth#lookupWrap()` to validate the lookup token before consuming it with `Auth#unwrap`. From documentation https://www.vaultproject.io/docs/concepts/response-wrapping.html#response-wrapping-token-validation

**Comment by steve-perkins** [comment]
PR merged, thanks!  There's a nice sized list of changes that has built up since 3.0.0 now, so I plan to cut a 3.1.0 release with all of them this week.
