### ISSUE TITLE
Keys with null values cause UnsupportedOperationException

### ISSUE THREAD

**Issue by kunickiaj** [BetterCloud/vault-java-driver#8]
When a `logical().read()` result includes a null value, the following error is thrown: `java.lang.UnsupportedOperationException: Not a string: null`

This is because the .asString() call fails.

One example where this is common is the aws backend as it returns 3 keys:
access_key
secret_key
security_token

security_token is always null if STS is not being used.

`member.getValue()` should include a `.isNull()` check before calling `.asString()` to ensure safety.

**Comment by steve-perkins** [comment]
Thanks for the report!  We'll add a check and get this fixed in the next release, which I expect will happen within the next week.
